### ISSUE TITLE
Attempt to make this the official Mac Riven client

### ISSUE THREAD

**Issue by 75th** [jfroy/rivenx#7]
Cyan is doing an [already-wildly-successful Kickstarter](https://www.kickstarter.com/projects/1252280491/myst-25th-anniversary-collection) to update all the Myst games for Myst's 25th anniversary. They're only officially targeting Windows 10, but because it's so successful, they have expressed their desire in multiple project updates to do something for Mac users, too.

Would it be okay if I drew their attention to this project, in the hopes that it can be made official? Or would you rather stay under the radar? I posted on one of their Facebook walls about it, but quickly deleted it when I realized I should ask first.

**Comment by jfroy** [comment]
I've been meaning to get in touch with them about it. That being said, the Riven X code base needs significant improvements to be viable for that Kickstarter. In particular, QuickTime needs to be replaced for a 64-bit compatible API. I don't have a lot of time to work on that, but I do have some.

I am also a backer on that kickstarter and I will get in touch with Cyan myself. You can send your own email if you wish.
